version: '3'
services:
  mysql:
    restart: always
    image: mysql:latest
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: cashcloud
      MYSQL_USER: desha
      MYSQL_PASSWORD: desha
    networks:
      - backend
    volumes:
      - 'cashcloud-mysql:/var/lib/mysql'
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-p toor" ]
      retries: 3
      timeout: 5s

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    networks:
      - backend
    volumes:
      - 'cashcloud-redis:/data'
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      retries: 3
      timeout: 5s

  phpmyadmin:
    platform: linux/x86_64
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: toor
    ports:
      - "8080:80"
    networks:
      - backend

  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '9000:9000'
    env_file:
      - ./.env
    depends_on:
      - mysql
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev
    networks:
      - backend
    restart: always

networks:
  backend:
    driver: bridge

volumes:
  cashcloud_api:
    driver: local
  cashcloud-redis:
    driver: local
  cashcloud-mysql:
    driver: local