version: '3'
services:
  mysql:
    image: mysql:latest
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: cashcloud
      MYSQL_USER: desha
      MYSQL_PASSWORD: desha
    networks:
      - backend

  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: toor
    ports:
      - "8080:80"
    networks:
      - backend

  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '9000:9000'
    env_file:
      - ./.env
    depends_on:
      - mysql
    volumes:
      - .:/usr/src/app
    command: npm run start:dev
    networks:
      - backend

networks:
  backend:
    driver: bridge